# Generated by Django 4.1.3 on 2022-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedNumbers',
            fields=[
                ('number', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('vin_code', models.CharField(max_length=17, unique=True)),
                ('car_model', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NumbersLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('log_date', models.DateField()),
                ('status', models.TextField()),
                ('media_path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('full_name', models.TextField()),
                ('password', models.TextField()),
                ('salt', models.CharField(max_length=5)),
                ('last_login', models.DateField()),
                ('role', models.TextField()),
            ],
        ),
    ]
