# Generated by Django 4.1.3 on 2022-11-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberslogs',
            name='media_path',
            field=models.TextField(),
        ),
    ]
